export type SeedPair = {
  hebrew: string;
  english: string;
};

export type SeedPack = {
  level: string;
  type: string | null;
  pairs: SeedPair[];
};

export const seedData: SeedPack[] = [
  {
    level: "Red",
    type: null,
    pairs: [
      { hebrew: "שָׁלוֹם", english: "Hello / Peace" },
      { hebrew: "תּוֹדָה", english: "Thank you" },
      { hebrew: "בֹּקֶר", english: "Morning" },
      { hebrew: "לַיְלָה", english: "Night" },
      { hebrew: "כֵּן", english: "Yes" },
      { hebrew: "לֹא", english: "No" },
      { hebrew: "מַיִם", english: "Water" },
      { hebrew: "בַּיִת", english: "House / Home" },
      { hebrew: "אִמָּא", english: "Mom" },
      { hebrew: "אַבָּא", english: "Dad" },
    ],
  },
  {
    level: "Orange",
    type: null,
    pairs: [
      { hebrew: "אֶחָד", english: "One" },
      { hebrew: "שְׁנַיִם", english: "Two" },
      { hebrew: "שְׁלוֹשָׁה", english: "Three" },
      { hebrew: "אָדֹם", english: "Red" },
      { hebrew: "כָּחֹל", english: "Blue" },
      { hebrew: "כֶּלֶב", english: "Dog" },
      { hebrew: "חָתוּל", english: "Cat" },
      { hebrew: "אֹכֶל", english: "Food" },
      { hebrew: "לֶחֶם", english: "Bread" },
      { hebrew: "חָלָב", english: "Milk" },
    ],
  },
  {
    level: "Pink",
    type: null,
    pairs: [
      { hebrew: "שְׁמִי", english: "My name is" },
      { hebrew: "מָה", english: "What" },
      { hebrew: "מִי", english: "Who" },
      { hebrew: "אֵיפֹה", english: "Where" },
      { hebrew: "מָתַי", english: "When" },
      { hebrew: "לָמָה", english: "Why" },
      { hebrew: "אֲנִי", english: "I" },
      { hebrew: "אַתָּה", english: "You (m.)" },
      { hebrew: "אַתְּ", english: "You (f.)" },
      { hebrew: "הוּא", english: "He" },
    ],
  },
  {
    level: "Yellow",
    type: null,
    pairs: [
      { hebrew: "טוֹב", english: "Good" },
      { hebrew: "רַע", english: "Bad" },
      { hebrew: "גָּדוֹל", english: "Big" },
      { hebrew: "קָטָן", english: "Small" },
      { hebrew: "חַם", english: "Hot" },
      { hebrew: "קַר", english: "Cold" },
      { hebrew: "יָפֶה", english: "Beautiful" },
      { hebrew: "חָדָשׁ", english: "New" },
      { hebrew: "יָשָׁן", english: "Old" },
      { hebrew: "פֹּה", english: "Here" },
    ],
  },
  {
    level: "Light Blue",
    type: null,
    pairs: [
      { hebrew: "מַה נִשְׁמָע", english: "What's up?" },
      { hebrew: "בְּסֵדֶר", english: "OK / Fine" },
      { hebrew: "בְּבַקָּשָׁה", english: "Please" },
      { hebrew: "סְלִיחָה", english: "Sorry / Excuse me" },
      { hebrew: "עוֹד", english: "More" },
      { hebrew: "קְצָת", english: "A little" },
      { hebrew: "הַיּוֹם", english: "Today" },
      { hebrew: "מָחָר", english: "Tomorrow" },
      { hebrew: "אֶתְמוֹל", english: "Yesterday" },
      { hebrew: "עַכְשָׁיו", english: "Now" },
    ],
  },
  {
    level: "Blue",
    type: null,
    pairs: [
      { hebrew: "אֲנִי רוֹצֶה", english: "I want" },
      { hebrew: "אֲנִי אוֹהֵב", english: "I love" },
      { hebrew: "בּוֹא", english: "Come" },
      { hebrew: "לֵךְ", english: "Go" },
      { hebrew: "תֵּן", english: "Give" },
      { hebrew: "קַח", english: "Take" },
      { hebrew: "דַּבֵּר", english: "Speak" },
      { hebrew: "שְׁמַע", english: "Listen" },
      { hebrew: "רְאֵה", english: "See" },
      { hebrew: "עֲשֵׂה", english: "Do / Make" },
    ],
  },
  {
    level: "Lime",
    type: null,
    pairs: [
      { hebrew: "חָבֵר", english: "Friend" },
      { hebrew: "מִשְׁפָּחָה", english: "Family" },
      { hebrew: "עֲבוֹדָה", english: "Work" },
      { hebrew: "בֵּית סֵפֶר", english: "School" },
      { hebrew: "עִיר", english: "City" },
      { hebrew: "רְחוֹב", english: "Street" },
      { hebrew: "זְמַן", english: "Time" },
      { hebrew: "שָׁעָה", english: "Hour" },
      { hebrew: "דַּקָּה", english: "Minute" },
      { hebrew: "שָׁנָה", english: "Year" },
    ],
  },
  {
    level: "Green",
    type: null,
    pairs: [
      { hebrew: "אֲנִי חוֹשֵׁב", english: "I think" },
      { hebrew: "אֲנִי יוֹדֵעַ", english: "I know" },
      { hebrew: "אֲנִי מֵבִין", english: "I understand" },
      { hebrew: "אֲנִי לֹא מֵבִין", english: "I don't understand" },
      { hebrew: "אֶפְשָׁר", english: "Possible / May I" },
      { hebrew: "צָרִיךְ", english: "Need to" },
      { hebrew: "חָשׁוּב", english: "Important" },
      { hebrew: "מְעַנְיֵן", english: "Interesting" },
      { hebrew: "קָשֶׁה", english: "Hard" },
      { hebrew: "קַל", english: "Easy" },
    ],
  },
  {
    level: "Dark Green",
    type: "Pack 1",
    pairs: [
      { hebrew: "לְמַרוֹת", english: "Despite" },
      { hebrew: "לְפִי", english: "According to" },
      { hebrew: "בִּגְלַל", english: "Because of" },
      { hebrew: "בְּעֶצֶם", english: "Actually" },
      { hebrew: "כַּנִּרְאֶה", english: "Probably" },
      { hebrew: "בְּטַח", english: "Surely" },
      { hebrew: "אוּלַי", english: "Maybe" },
      { hebrew: "בְּכָל מִקְרֶה", english: "In any case" },
      { hebrew: "לְדַעְתִּי", english: "In my opinion" },
      { hebrew: "בְּעִקָּר", english: "Mainly" },
    ],
  },
  {
    level: "Dark Green",
    type: "Pack 2",
    pairs: [
      { hebrew: "הַצָּעָה", english: "Proposal" },
      { hebrew: "הַחְלָטָה", english: "Decision" },
      { hebrew: "מַשָּׂא וּמַתָּן", english: "Negotiation" },
      { hebrew: "הֶסְכֵּם", english: "Agreement" },
      { hebrew: "תְּנַאי", english: "Condition" },
      { hebrew: "מַטָּרָה", english: "Goal" },
      { hebrew: "אֶתְגָּר", english: "Challenge" },
      { hebrew: "הַזְדַּמְּנוּת", english: "Opportunity" },
      { hebrew: "פִּתְרוֹן", english: "Solution" },
      { hebrew: "תּוֹצָאָה", english: "Result" },
    ],
  },
  {
    level: "Dark Green",
    type: "Pack 3",
    pairs: [
      { hebrew: "תַּרְבּוּת", english: "Culture" },
      { hebrew: "מָסוֹרֶת", english: "Tradition" },
      { hebrew: "חֶבְרָה", english: "Society" },
      { hebrew: "זֶהוּת", english: "Identity" },
      { hebrew: "שַׁיָּכוּת", english: "Belonging" },
      { hebrew: "מְגוּוָן", english: "Diversity" },
      { hebrew: "דֵּעָה", english: "Opinion" },
      { hebrew: "וִיכּוּחַ", english: "Debate" },
      { hebrew: "פְּשָׁרָה", english: "Compromise" },
      { hebrew: "כָּבוֹד", english: "Respect" },
    ],
  },
  {
    level: "Dark Green",
    type: "Pack 4",
    pairs: [
      { hebrew: "חִנּוּךְ", english: "Education" },
      { hebrew: "לְמִידָה", english: "Learning" },
      { hebrew: "יֵדַע", english: "Knowledge" },
      { hebrew: "מִיּוּמָנוּת", english: "Skill" },
      { hebrew: "נִסָּיוֹן", english: "Experience" },
      { hebrew: "הִתְפַּתְּחוּת", english: "Development" },
      { hebrew: "צְמִיחָה", english: "Growth" },
      { hebrew: "הַשְׁפָּעָה", english: "Influence" },
      { hebrew: "מוֹטִיבָצְיָה", english: "Motivation" },
      { hebrew: "הִישָׂג", english: "Achievement" },
    ],
  },
  {
    level: "Turquoise",
    type: "Pack 1",
    pairs: [
      { hebrew: "נוֹף", english: "View / Landscape" },
      { hebrew: "טֶבַע", english: "Nature" },
      { hebrew: "יָם", english: "Sea" },
      { hebrew: "הַר", english: "Mountain" },
      { hebrew: "יַעַר", english: "Forest" },
      { hebrew: "שֶׁמֶשׁ", english: "Sun" },
      { hebrew: "יָרֵחַ", english: "Moon" },
      { hebrew: "כּוֹכָב", english: "Star" },
      { hebrew: "גֶּשֶׁם", english: "Rain" },
      { hebrew: "רוּחַ", english: "Wind" },
    ],
  },
  {
    level: "Turquoise",
    type: "Pack 2",
    pairs: [
      { hebrew: "מוּזֵיאוֹן", english: "Museum" },
      { hebrew: "תַּעֲרוּכָה", english: "Exhibition" },
      { hebrew: "סֵפֶר", english: "Book" },
      { hebrew: "סִפּוּר", english: "Story" },
      { hebrew: "שִׁיר", english: "Poem / Song" },
      { hebrew: "תְּאָטְרוֹן", english: "Theater" },
      { hebrew: "סֶרֶט", english: "Movie" },
      { hebrew: "מוּזִיקָה", english: "Music" },
      { hebrew: "אֹמָנוּת", english: "Art" },
      { hebrew: "יְצִירָה", english: "Creation / Work" },
    ],
  },
  {
    level: "Turquoise",
    type: "Pack 3",
    pairs: [
      { hebrew: "בִּישׁוּל", english: "Cooking" },
      { hebrew: "מַתְכּוֹן", english: "Recipe" },
      { hebrew: "טַעַם", english: "Taste" },
      { hebrew: "רֵיחַ", english: "Smell" },
      { hebrew: "מִטְבָּח", english: "Kitchen" },
      { hebrew: "אֲרוּחָה", english: "Meal" },
      { hebrew: "אֲרוּחַת בֹּקֶר", english: "Breakfast" },
      { hebrew: "אֲרוּחַת עֶרֶב", english: "Dinner" },
      { hebrew: "מִסְעָדָה", english: "Restaurant" },
      { hebrew: "טִבְעוֹנִי", english: "Vegan" },
    ],
  },
  {
    level: "Turquoise",
    type: "Pack 4",
    pairs: [
      { hebrew: "טִיּוּל", english: "Trip / Hike" },
      { hebrew: "מַסְלוּל", english: "Route / Trail" },
      { hebrew: "מַפָּה", english: "Map" },
      { hebrew: "מַדְרִיךְ", english: "Guide" },
      { hebrew: "תַּרְמִיל", english: "Backpack" },
      { hebrew: "מַחֲנָאוּת", english: "Camping" },
      { hebrew: "שְׁמוּרַת טֶבַע", english: "Nature reserve" },
      { hebrew: "נְקוּדַת תִּצְפִּית", english: "Viewpoint" },
      { hebrew: "מִזְרוֹן", english: "Sleeping bag" },
      { hebrew: "פָּנָס", english: "Flashlight" },
    ],
  },
  {
    level: "Indigo",
    type: "Pack 1",
    pairs: [
      { hebrew: "פְּגִישָׁה", english: "Meeting" },
      { hebrew: "מַצָּגֶת", english: "Presentation" },
      { hebrew: "דוֹחַ", english: "Report" },
      { hebrew: "פְּרוֹיֶקְט", english: "Project" },
      { hebrew: "לוּחַ זְמַנִים", english: "Schedule" },
      { hebrew: "דֵּד לָיין", english: "Deadline" },
      { hebrew: "צֶוֶת", english: "Team" },
      { hebrew: "מְנַהֵל", english: "Manager" },
      { hebrew: "לָקוֹחַ", english: "Client" },
      { hebrew: "תַּקְצִיב", english: "Budget" },
    ],
  },
  {
    level: "Indigo",
    type: "Pack 2",
    pairs: [
      { hebrew: "רֶגֶשׁ", english: "Emotion" },
      { hebrew: "שִׂמְחָה", english: "Joy" },
      { hebrew: "עֶצֶב", english: "Sadness" },
      { hebrew: "כַּעַס", english: "Anger" },
      { hebrew: "פַּחַד", english: "Fear" },
      { hebrew: "תִּקְוָה", english: "Hope" },
      { hebrew: "אִכְזָבָה", english: "Disappointment" },
      { hebrew: "גַּאֲוָה", english: "Pride" },
      { hebrew: "בּוּשָׁה", english: "Shame" },
      { hebrew: "אֶמְפַּתְיָה", english: "Empathy" },
    ],
  },
  {
    level: "Indigo",
    type: "Pack 3",
    pairs: [
      { hebrew: "רְפוּאָה", english: "Medicine" },
      { hebrew: "בְּרִיאוּת", english: "Health" },
      { hebrew: "רוֹפֵא", english: "Doctor" },
      { hebrew: "תְּרוּפָה", english: "Medication" },
      { hebrew: "טִפּוּל", english: "Treatment" },
      { hebrew: "תְּסַמִּין", english: "Symptom" },
      { hebrew: "כְּאֵב", english: "Pain" },
      { hebrew: "מְנוּחָה", english: "Rest" },
      { hebrew: "תְּזוּנָה", english: "Nutrition" },
      { hebrew: "סְפּוֹרְט", english: "Sport" },
    ],
  },
  {
    level: "Indigo",
    type: "Pack 4",
    pairs: [
      { hebrew: "פּוֹלִיטִיקָה", english: "Politics" },
      { hebrew: "בְּחִירוֹת", english: "Elections" },
      { hebrew: "צֶדֶק", english: "Justice" },
      { hebrew: "חֹק", english: "Law" },
      { hebrew: "זְכוּת", english: "Right" },
      { hebrew: "חוֹבָה", english: "Duty" },
      { hebrew: "שְׁווֹיוֹן", english: "Equality" },
      { hebrew: "חֵרוּת", english: "Freedom" },
      { hebrew: "דֵּמוֹקְרַטְיָה", english: "Democracy" },
      { hebrew: "אֶזְרָחוּת", english: "Citizenship" },
    ],
  },
  {
    level: "Indigo",
    type: "Pack 5",
    pairs: [
      { hebrew: "טֶכְנוֹלוֹגְיָה", english: "Technology" },
      { hebrew: "חַדָּשָׁנוּת", english: "Innovation" },
      { hebrew: "סְטָארְטָאפּ", english: "Startup" },
      { hebrew: "הַשְׁקָעָה", english: "Investment" },
      { hebrew: "שׁוּק", english: "Market" },
      { hebrew: "תַּחֲרוּת", english: "Competition" },
      { hebrew: "אִסְטְרָטֶגְיָה", english: "Strategy" },
      { hebrew: "מִיתוּג", english: "Branding" },
      { hebrew: "שִׁיוּק", english: "Marketing" },
      { hebrew: "מְכִירוֹת", english: "Sales" },
    ],
  },
  {
    level: "Indigo",
    type: "Pack 6",
    pairs: [
      { hebrew: "סְבִיבָה", english: "Environment" },
      { hebrew: "קַיְּמוּת", english: "Sustainability" },
      { hebrew: "זִיהוּם", english: "Pollution" },
      { hebrew: "מִחְזוּר", english: "Recycling" },
      { hebrew: "אַקְלִים", english: "Climate" },
      { hebrew: "מַשְׁאָבִים", english: "Resources" },
      { hebrew: "שִׁמּוּר", english: "Conservation" },
      { hebrew: "אַחֲרָיוּת", english: "Responsibility" },
      { hebrew: "עָתִיד", english: "Future" },
      { hebrew: "דּוֹר", english: "Generation" },
    ],
  },
  {
    level: "Purple",
    type: null,
    pairs: [
      { hebrew: "עַל הַפָּנִים", english: "Terrible (slang)" },
      { hebrew: "סַבָּבָה", english: "Cool / OK" },
      { hebrew: "יָאלְלָה", english: "Come on / Let's go" },
      { hebrew: "חֲבָל עַל הַזְּמַן", english: "Amazing (slang)" },
      { hebrew: "נוּ", english: "Well / So" },
      { hebrew: "בְּקִיצּוּר", english: "In short" },
      { hebrew: "בָּרוּר", english: "Clear / Of course" },
      { hebrew: "תַּכְלִיס", english: "Actually / In practice" },
      { hebrew: "אֵין מָצָב", english: "No way" },
      { hebrew: "מַגְנִיב", english: "Cool" },
    ],
  },
];
